server:
  port: 9900
  address: localhost
springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui.html # 自定义路径，默认为"/swagger-ui/index.html"
api-docs:
  title: WlJava-API
  description: WlJava Server
  version: v1.0.0
logging:
  config: classpath:logback.xml
spring:
  #datasource相关配置
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: "12345678"
    url: "jdbc:mysql://localhost:3306/LearnJava"
    type: com.alibaba.druid.pool.DruidDataSource
    #druid 连接池配置项
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  #Redis相关配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      jedis:
        #Redis连接池配置
        pool:
          max-active: 8 #最大连接数
          max-wait: 1ms #连接池最大阻塞等待时间
          max-idle: 4 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
    table-underline: false
  global-config:
    db-config:
      column-underline: false
