server:
  port: 8822
  address: 192.168.0.3
springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui.html # 自定义路径，默认为"/swagger-ui/index.html"
api-docs:
  title: Psag-API
  description: Psag Server
  version: v1.0.0
logging:
  config: classpath:logback.xml